version: '3.8'

services:
  jogak_backend_app:
    image: mallangc/jogakjogak-backend:1.0.0
    container_name: jogak-backend
    environment:
      DB_URL: ${DB_URL}
      DB_META_URL: ${DB_META_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      KAKAO_ADMIN_KEY: ${KAKAO_ADMIN_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_URL: ${OPENAI_API_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      EMAIL_ID: ${EMAIL_ID}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URL}
      EMAIL_AES_KEY: ${EMAIL_AES_KEY}
      PHONE_AES_KEY: ${PHONE_AES_KEY}
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro