spring:
  application:
  name: jogakjogak

  datasource-main:
    jdbc-url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource-meta:
    jdbc-url: ${DB_META_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: auto
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope:
              - account_email
              - profile_nickname
              - name
              - phone_number
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-name: Kakao
            client-authentication-method: client_secret_post

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
kakao:
  admin-key: ${KAKAO_ADMIN_KEY}

jwt:
  secret-key: ${JWT_SECRET_KEY}

openai:
  api:
    key: ${OPENAI_API_KEY}
    url: ${OPENAI_API_URL}
    model: gpt-4-turbo
    max-tokens: 1000