spring:
  application:
   name: jogakjogak

  datasource-main:
    jdbc-url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource-meta:
    jdbc-url: ${DB_META_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope:
              - account_email
              - profile_nickname
              - name
              - phone_number
            authorization-grant-type: authorization_code
            redirect-uri: https://jogakjogak.com/login/oauth2/code/google
            client-name: Kakao
            client-authentication-method: client_secret_post

          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
            client-name: Google

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

kakao:
  admin-key: ${KAKAO_ADMIN_KEY}
  redirect-uri: ${KAKAO_REDIRECT_URI}

jwt:
  secret-key: ${JWT_SECRET_KEY}

openai:
  api:
    key: ${OPENAI_API_KEY}
    url: ${OPENAI_API_URL}
    model: gpt-4-turbo
    max-tokens: 1000

server:
  port: 8080
  
gemini:
  api:
    key: ${GEMINI_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: "always"
logging:
  level:
    org.flywaydb: DEBUG
