name: CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
# 코드를 pull하기 위한 읽기 권한 부여
# JaCoCo로 리포트를 생성하기 위한 쓰기 권한 부여
permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SPRING_PROFILES_ACTIVE: test
      _JAVA_OPTIONS: "-Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses"

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 3306:3306
        volumes:
          - ${{ github.workspace }}/.github/workflows/init_dbs.sh:/docker-entrypoint-initdb.d/init_dbs.sh

    steps:
      - uses: actions/checkout@v4

      - name: Grant execute permission to init_dbs.sh
        run: chmod +x ${{ github.workspace }}/.github/workflows/init_dbs.sh

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # gradle wrapper에 대한 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # gradle 빌드관련 캐시와 빌드 결과물을 초기화
      - name: Clean Gradle Cache and Build
        run: |
          ./gradlew --stop
          rm -rf ~/.gradle/caches/
          rm -rf build/

      # 7.6.4버전으로 gradle 세팅 (JaCoCo와 호환성이 좋은 버전으로 세팅)
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '7.6.4'

      - name: Set Database Connection Environment Variables
        run: |
          echo "TEST_DB_USERNAME=root" >> $GITHUB_ENV 
          echo "TEST_DB_PASSWORD=rootpassword" >> $GITHUB_ENV

      - name: Wait for MySQL services to be ready
        run: |
          echo "Explicitly waiting for MySQL service (db:3306) to be ready..."
          for i in $(seq 1 20); do
            if mysqladmin ping -h 127.0.0.1 -P 3306 -u root -prootpassword --silent; then
              echo "MySQL server (db:3306) is up after $i seconds."
              break
            fi
            echo "Waiting for MySQL server (db:3306)... ($i/20)"
            sleep 1
          done
          mysqladmin ping -h 127.0.0.1 -P 3306 -u root -prootpassword || { echo "MySQL server (db:3306) is not ready after max wait time!"; exit 1; }

          echo "Waiting for test_main_db to be accessible..."
          for i in $(seq 1 10); do
            if mysql -h 127.0.0.1 -P 3306 -u root -prootpassword -e 'USE test_main_db;' &> /dev/null; then
              echo "test_main_db is accessible after $i seconds."
              break
            fi
            echo "Waiting for test_main_db... ($i/10)"
            sleep 1
          done
          mysql -h 127.0.0.1 -P 3306 -u root -p rootpassword -e 'USE test_main_db;' || { echo "test_main_db is not accessible after max wait time!"; exit 1; }

          echo "Waiting for test_meta_db to be accessible..."
          for i in $(seq 1 10); do
            if mysql -h 127.0.0.1 -P 3306 -u root -prootpassword -e 'USE test_meta_db;' &> /dev/null; then
              echo "test_meta_db is accessible after $i seconds."
              break
            fi
            echo "Waiting for test_meta_db... ($i/10)"
            sleep 1
          done
          mysql -h 127.0.0.1 -P 3306 -u root -p rootpassword -e 'USE test_meta_db;' || { echo "test_meta_db is not accessible after max wait time!"; exit 1; }

      # 테스트 전 애플리케이션 빌드
      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Check application-test.yml exists
        run: cat src/test/resources/application-test.yml || echo "application-test.yml not found"

      # 테스트 진행
      - name: Test with Gradle
        env:
          SPRING_PROFILES_ACTIVE: test
        run: ./gradlew test --info

      # 테스트를 기반으로 JaCoCo 리포트 작성
      - name: Generate JaCoCo Report
        run: ./gradlew jacocoTestReport

      # JaCoCo리포트를 PR댓글로 남기기
      - name: JaCoCo Report to PR
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Code Coverage'
          update-comment: true

      # 모든 스텝 종료 후 컨테이너 로그 출력 (에러 발생 시 유용)
      - name: Print Docker container logs (for debugging)
        if: always() # 실패해도 항상 로그 출력
        run: |
          echo "Listing all Docker containers:"
          docker ps -a
          echo "--- Attempting to get logs for all 'mysql:8.0' containers ---"
          ALL_MYSQL_CONTAINER_IDS=$(docker ps -a -q -f "ancestor=mysql:8.0")
          if [ -n "$ALL_MYSQL_CONTAINER_IDS" ]; then
            for CONTAINER_ID in $ALL_MYSQL_CONTAINER_IDS; do
              echo "--- Logs for container ID: $CONTAINER_ID ---"
              docker logs --details "$CONTAINER_ID" || true
              echo "--- End of logs for container ID: $CONTAINER_ID ---"
            done
          else
            echo "No 'mysql:8.0' containers found."
          fi
          echo "--- End of Docker container logs ---"